apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecart-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
        - name: backend
          image: yogirajdeshpande/demo:2
          imagePullPolicy: Always
          env:
          - name: MONGO_CONN_STR
            value: mongodb://mongodb-svc:27017/todo?directConnection=true
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
      ports:
      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ecart-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
